# Generated by Django 5.2.13 on 2026-04-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="max_retries",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="job",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
    ]
